### ISSUE TITLE
Gather, Become ...

### ISSUE THREAD

**Issue by Cdrix** [Ponzel/FoundersFortuneLocalization#10]
1) First picture in English 

![Screenshot_6](https://user-images.githubusercontent.com/40391221/56598729-60fb8500-65f5-11e9-9f57-1715274d5e0c.png)
![Screenshot_7](https://user-images.githubusercontent.com/40391221/56598731-61941b80-65f5-11e9-8852-cfe107a2521e.png)

**Comment by Ponzel** [comment]
Fixed!
