### ISSUE TITLE
FOR DEV : Translation

### ISSUE THREAD

**Issue by Cdrix** [Ponzel/FoundersFortuneLocalization#14]
1) The words "pommes" is missing

![Screenshot_2](https://user-images.githubusercontent.com/40391221/56847151-c68e9080-68d7-11e9-83f8-735b1d917a06.png)

**Comment by Cdrix** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/40391221/56847455-68fc4300-68db-11e9-9587-481f77d1d17a.png)
![Screenshot_4](https://user-images.githubusercontent.com/40391221/56847459-6e598d80-68db-11e9-9168-32b35b86bf07.png)

**Comment by Cdrix** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/40391221/56847508-f5a70100-68db-11e9-87b4-cb44f30d76ea.png)

**Comment by Cdrix** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/40391221/56847534-6b12d180-68dc-11e9-9099-748affbb3f33.png)

**Comment by Ponzel** [comment]
Thanks for the detailed annotations. Will fix these before the next update.

**Comment by Cdrix** [comment]
1) change is always in english

![Screenshot_2](https://user-images.githubusercontent.com/40391221/56852877-e5654500-6920-11e9-8e83-a3697742d40a.png)

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/56852931-8522d300-6921-11e9-8687-3ab62e329733.png)

**Comment by Cdrix** [comment]
1) words are missing "sauvegarder les" "......"

![image](https://user-images.githubusercontent.com/40391221/56852939-9835a300-6921-11e9-98f7-bc3474ac523d.png)

**Comment by Cdrix** [comment]
1) For all the texts in the encyclopedia, possibility to justify the text ?

![image](https://user-images.githubusercontent.com/40391221/56852946-c1563380-6921-11e9-939d-b1ff1d8f9f79.png)

**Comment by Ponzel** [comment]
justify the text? Do you mean making the text align on the right side as well?

**Comment by Cdrix** [comment]
Yes ;)

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/56899353-84aa4980-6a93-11e9-81c6-30f7301c2b2e.png)

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/56900638-950ff380-6a96-11e9-9ce7-fb26dec02136.png)

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/56912289-4589f180-6aaf-11e9-98d5-c5fb5921816d.png)

**Comment by Ponzel** [comment]
About the "community translation is available now" box:
This box dynamically updates based on values that are downloaded from our server. Which means we can change this message in real time for every player.
That means this text is not part of any .json file and can not be translated.
For practical reasons, we'll just keep it in english for everyone, otherwise we'd need to make a more complicated system and check back with all the community translators every time we want to change that message.

**Comment by Ponzel** [comment]
Turns out we can't easily justify the text. Skipping for now as it's not important.

**Comment by Ponzel** [comment]
Alright, fixed everything. There are a couple of new labels, so you'll need to translate them before it's actually working. Thanks for the reports 👍
