### ISSUE TITLE
Mots à modifier

### ISSUE THREAD

**Issue by Cdrix** [Ponzel/FoundersFortuneLocalization#15]

**Comment by Cdrix** [comment]
Modifier Mirador et Mirador Solide

**Comment by JordanPANDA** [comment]
### **_Done._**

**Mirrador** reste **Mirrador**
**Mirrador solide** devient **Tour**

**Comment by Chaveex** [comment]
A modifier (gameObjects.json#L1852
**facielment** devient **facilement**

(gameObjects.json) #L1852 sur Master && #L1789 sur la branche Alpha_7

![InkedFounders Fortune2019-05-09-00-10-30_LI](https://user-images.githubusercontent.com/24280480/57411860-15e59280-71ef-11e9-8f73-d4ef1253b8c6.jpg)

**Comment by Ponzel** [comment]
is this done?
If yes, please close the issue.
