### ISSUE TITLE
Panel too small

### ISSUE THREAD

**Issue by JordanPANDA** [Ponzel/FoundersFortuneLocalization#17]
![unknown](https://user-images.githubusercontent.com/35566620/57201194-e25bfb80-6f95-11e9-9640-ea27e8f16941.png)
**Panel too small for big translation** maybe i **suggest dynamic font size or dynamic panel size**
see screen for see what is the problem

**Comment by Patrador** [comment]
![image](https://user-images.githubusercontent.com/43299105/57250452-c3b63d00-7047-11e9-8721-71f4ffd29475.png)
same here

**Comment by Patrador** [comment]
![image](https://user-images.githubusercontent.com/43299105/57314684-6d520880-70f2-11e9-9096-114fa4caad97.png)

**Comment by Ponzel** [comment]
All fixed!
Thanks for the reports.
