### ISSUE TITLE
FR - Panel too little

### ISSUE THREAD

**Issue by Cdrix** [Ponzel/FoundersFortuneLocalization#21]

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/58502304-8f392b00-8186-11e9-9e76-ebe3d02b098a.png)

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/58502353-a37d2800-8186-11e9-9fc0-b6f8b4d61862.png)

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/58502383-b2fc7100-8186-11e9-98b9-587dd66bd0b0.png)

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/58502439-cb6c8b80-8186-11e9-8689-17e7b68e518a.png)

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/58502594-18e8f880-8187-11e9-8140-7e7c806725f9.png)

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/58507083-2efbb680-8191-11e9-8b17-84955e0a3557.png)

**Comment by Cdrix** [comment]
![image](https://user-images.githubusercontent.com/40391221/58507191-741fe880-8191-11e9-934e-e599c4c66273.png)

**Comment by Ponzel** [comment]
All fixed! Thanks for reporting @Cdrix.
Open a new issue when you find more.
