### ISSUE TITLE
Value replacement issue

### ISSUE THREAD

**Issue by Chaveex** [Ponzel/FoundersFortuneLocalization#27]
in expectation.json, "ownsSleepingSpot"
in the spanish text "spanish": "Es dueñ%oA% de un lugar para dormir"
the %oA% is not replaced in game

![FoundersFortune_2019-05-30-13-36-20_cut](https://user-images.githubusercontent.com/24280480/58672931-6e6d0300-8349-11e9-9d16-6e5496ef1d46.jpg)

**Comment by Ponzel** [comment]
fixed
