### ISSUE TITLE
Panel too small - Alpha 7.4

### ISSUE THREAD

**Issue by Patrador** [Ponzel/FoundersFortuneLocalization#28]
![FF_bug2](https://user-images.githubusercontent.com/43299105/58808838-15d48900-861b-11e9-9d78-4661596a59d2.png)
![FF_bug3](https://user-images.githubusercontent.com/43299105/58808841-15d48900-861b-11e9-9391-2a2f25bd1bcf.png)
![FF_bug4](https://user-images.githubusercontent.com/43299105/58808842-15d48900-861b-11e9-87f8-a01be6dd34e5.png)
![FF_bug5](https://user-images.githubusercontent.com/43299105/58808844-166d1f80-861b-11e9-81d5-b26f1df0bdc5.png)
![ff_bug](https://user-images.githubusercontent.com/43299105/58908981-3f241080-8712-11e9-8499-86b598861268.png)

**Comment by Ponzel** [comment]
all fixed, thanks for the reports
