### ISSUE TITLE
Gender bugs

### ISSUE THREAD

**Issue by Patrador** [Ponzel/FoundersFortuneLocalization#29]
![FF_bug1](https://user-images.githubusercontent.com/43299105/58809136-a4490a80-861b-11e9-9123-746dfa750f33.png)
![FF_bug6](https://user-images.githubusercontent.com/43299105/58809137-a4490a80-861b-11e9-98de-3917ffba31c2.png)

**Comment by Ponzel** [comment]
fixed, thanks for reporting.
