### ISSUE TITLE
Rus Uk localization

### ISSUE THREAD

**Issue by IDeadCatI** [Ponzel/FoundersFortuneLocalization#31]

**Comment by IDeadCatI** [comment]
[
![Записати](https://user-images.githubusercontent.com/47074345/60770020-33e04e00-a0df-11e9-8fe5-c0ac0b515c44.PNG)
](url)

**Comment by IDeadCatI** [comment]
![2131231](https://user-images.githubusercontent.com/47074345/60771401-5e86d280-a0f0-11e9-8b80-f8c7ffce50bf.PNG)
rus+UK trans.

**Comment by IDeadCatI** [comment]
![2131324344321](https://user-images.githubusercontent.com/47074345/60771510-e3262080-a0f1-11e9-8173-e280b93ab112.PNG)
uk trans.

**Comment by IDeadCatI** [comment]
![Без імені](https://user-images.githubusercontent.com/47074345/61177650-4842b000-a5e3-11e9-8597-485bf1570e0b.png)

**Comment by IDeadCatI** [comment]
![image](https://user-images.githubusercontent.com/47074345/61185986-61da0b00-a668-11e9-847a-dfefe641398f.png)

**Comment by IDeadCatI** [comment]
![image](https://user-images.githubusercontent.com/47074345/61186439-322e0180-a66e-11e9-8079-486df9166955.png)

**Comment by Ponzel** [comment]
All fixed except the last one. That's failing because this expression isn't present in genderDictionary.json.
You should be able to fix that yourself.

Thanks for the reports!
Close this issue when your done.
