### ISSUE TITLE
Errors with displaying Russian translation

### ISSUE THREAD

**Issue by dimon7147** [Ponzel/FoundersFortuneLocalization#32]
![unknown](https://user-images.githubusercontent.com/20266345/60842162-26f55480-a1dc-11e9-86e3-935a633bb1d0.png)

**Comment by dimon7147** [comment]
Also this buttons untranslatable
![unknown (2)](https://user-images.githubusercontent.com/20266345/60845615-91f75900-a1e5-11e9-84b2-573932c7363e.png)

**Comment by Ponzel** [comment]
fixed both of these
