### ISSUE TITLE
alpha8beta

### ISSUE THREAD

**Issue by Cdrix** [Ponzel/FoundersFortuneLocalization#34]
![image](https://user-images.githubusercontent.com/40391221/61148949-3af0cd00-a4e0-11e9-8964-3caa7042017e.png)
![image](https://user-images.githubusercontent.com/40391221/61148958-40e6ae00-a4e0-11e9-9d4a-822157b2eceb.png)

**Comment by dimon7147** [comment]
![image](https://user-images.githubusercontent.com/20266345/61158683-5ff63780-a502-11e9-9866-20974ea8948b.png)
![image](https://user-images.githubusercontent.com/20266345/61158688-64baeb80-a502-11e9-9afc-a07c3b5e0f60.png)
Same thing with russian translate

**Comment by Ponzel** [comment]
fixed, thanks for the report
