### ISSUE TITLE
I think Need to add frames to the background

### ISSUE THREAD

**Issue by IDeadCatI** [Ponzel/FoundersFortuneLocalization#36]
![213](https://user-images.githubusercontent.com/47074345/61186694-f0528a80-a670-11e9-8d7a-c2dfbd9ca239.jpg)

**Comment by Ponzel** [comment]
Hi @IDeadCatI, this kind of feedback doesn't really fit into the translation issues section.

You can add this feedback in the #suggestions channel on the Discord. Thank you.
