### ISSUE TITLE
"Beauty" text cut off in Russian translate (Alpha 8)

### ISSUE THREAD

**Issue by dimon7147** [Ponzel/FoundersFortuneLocalization#37]
![image](https://user-images.githubusercontent.com/20266345/61189596-70d8b180-a698-11e9-9467-3eca6fc63c26.png)

**Comment by dimon7147** [comment]
![image](https://user-images.githubusercontent.com/20266345/61189712-e8f3a700-a699-11e9-91dc-679137cb1c62.png)
Text with information about the necessary resources for construction overlaps each other.

**Comment by Ponzel** [comment]
@dimon7147  Is there any chance you can make the text any smaller?
Otherwise have to reduce the font size quite a bit I'm guessing.

**Comment by Burnwald** [comment]
>Is there any chance you can make the text any smaller?

Может - "Красота" и просто "Руда" или "Железо" ?

**Comment by dimon7147** [comment]
> @dimon7147 Is there any chance you can make the text any smaller?
> Otherwise have to reduce the font size quite a bit I'm guessing.

"Beauty" will be replaced to "Красота" and it's okay, but with second - need to make smaller font.

**Comment by Ponzel** [comment]
alright, changed it. I will close this issue now and you can change the beauty thing. Thanks.
