### ISSUE TITLE
English grammar corrections to Effects.json

### ISSUE THREAD

**Issue by aiydee** [Ponzel/FoundersFortuneLocalization#40]
"effectDesc_Starving": {
existing	"english": "%firstName% didn't eat in a long time. %cap-heShe% needs to find something to eat soon in order to survive.",

correction	"english": "%firstName% hasn't eaten in a long time. %cap-heShe% needs to find something to eat soon in order to survive.",

"effectDesc_AllergicReaction": {
existing	"english": "%firstName% had to eat food %heShe% is allergic to. Now %hisHer% body has an allergic reaction.",

correction	"english": "%firstName% has eaten food %heShe% is allergic to. Now %hisHer% body has had an allergic reaction.",

"effectTitle_SmallFoodRationsSlowness": {
existing	"english": "Slow work",

correction	"english": "Works slowly",

"effectTitle_LegHurt": {
existing	"english": "Hurt leg: Slow walking",

correction	"english": "Hurt leg: Walks slowly",

"effectTitle_ArmHurt": {
existing	"english": "Hurt arm: Slow working",

correction	"english": "Hurt arm: Works slowly",

**Comment by Ponzel** [comment]
Thanks.
"had to eat" vs "has eaten": I'd like to express that the colonist was forced to eat it (because nothing else was available). What do you think?

**Comment by aiydee** [comment]
That's a really good question.

You are trying to imply an imperative.  But in English with that line it
doesn't sound like they were 'forced' to eat it.
I know it sounds weird, but this is where English sucks.

I think something like "<colonist> had no choice but to eat" would be a
good idea.
It implies a 'there is a consequence to the decision'.

Hell.  I had to eat soup tonight.  I hate soup.  But there are no
consequences (Unless I refuse then I have to answer to the wife).

Sorry, but I feel there is no shortcut on this.  The sentence needs to
imply there is a consequence to the decision.

Dave

**Comment by Ponzel** [comment]
fixed
