### ISSUE TITLE
English grammar corrections for encyclopedia.json

### ISSUE THREAD

**Issue by aiydee** [Ponzel/FoundersFortuneLocalization#41]
"helpMenuText_research": {
		"english": "Your scholars come up with new technologies by studying the magic crystals scattered all around your settlement. Send out miners to collect some and build a book stand so your scholars may read up on techniques to analize the crystals. Make sure to select the next technology in the research panel in the top right corner.",

Please correct spelling of Analize to Analyse 

	"helpMenuText_foodProduction": {
Existing	"english": "Food matters. Good food makes colonists happy, wrong food makes colonists sick, little food makes colonists slow, and no food makes colonists die. So make sure you've got your production chain set up to provide for everyone!",

Correction	"english": "Food matters. Good food makes colonists happy, bad food makes colonists sick, little food makes colonists slow, and no food means colonists will die. So, make sure you've got your production chain set up to provide for everyone!",

helpMenuText_foodProduction_farming": {
existing	"english": "Everything begins in the fields, where industrious farmers spend their days caring for your crops. Depending on the season, they can sow a different selection of plants for food or medicinal purposes. Plants grow no matter how well you care for them, but good farmers use their watering cans to keep them growing optimally and increase their yield a lot. 
Now before you start planting like crazy, one last word of warning: All plants that don't get harvested before the end of their season will die without yielding any food to your colony!
Happy farming!.",		

correction	"english": "Everything begins in the fields, where industrious farmers spend their days caring for your crops. Depending on the season, they can sow a different selection of plants for food or medicinal purposes. Plants grow no matter how well you care for them, but good farmers use their watering cans to keep them growing optimally and increase their yield significantly. 
Now before you start planting like crazy, one last word of warning: All plants that don't get harvested before the end of their season will die without yielding any food for your colony!
Happy farming!.",

"helpMenuText_foodProduction_expectations": {
Existing	"english": "Colonists can deal with a lot of hardship, but they are not dumb. When your colony grows in size and numbers, they will start to expect better food than just eating raw plants. Using the campfire or the kitchen you can make meals of higher quality for demanding colonists. If you can run a bakery as well, they will welcome the variety!
Some colonists have favorite meals and get a mood boost if they can get it. Others are allergic to some types of food and will avoid them at all cost. If there is nothing else available, they may be forced to eat it anyways - resulting in an allergic reaction.",
		
This one is different.  Dumb is a trait.  And you say "Dumb" in the existing.  You could argue that some ARE dumb.  So I offer a suggestion instead.
Suggestion	"english": "Colonists can deal with a lot of hardship, but they are not stupid. When your colony grows in size and numbers, they will start to expect better food rather than just eating raw plants. Using the campfire or the kitchen you can make meals of higher quality for demanding colonists. If you can run a bakery as well, they will welcome the variety!
Some colonists have favorite meals and get a mood boost if they can get it. Others are allergic to some types of food and will avoid them at all cost. If there is nothing else available, they may be forced to eat it anyways - resulting in an allergic reaction.",
		

"helpMenuText_foodProduction_bugs": {
Existing	"english": "Every year, the dreaded bugs pose a serious danger to your harvest. If a bug infestation is detected, your colonists need to be quick and remove all affected plants before the infestation spreads. You can lose all your work in seconds!",

Correction	"english": "Every year, the dreaded bugs pose a serious danger to your harvest. If a bug infestation is detected, your colonists need to be quick and remove all affected plants before the infestation spreads. You could lose all your work in seconds!",

"helpMenuText_health": {
Existing	"english": "There are a lot of bad things that can happen to hard working colonists.
The most basic remedy is giving the poor little guys some time to rest. Laying in bed offers their the bodies some time to regenerate slowly. Have a look at the status panel (heart icon) to see details about the health state.",

Correction	"english": "There are a lot of bad things that can happen to hard working colonists.
The most basic remedy is giving the poor little guys some time to rest. Laying in bed offers their the bodies some time to regenerate slowly. Have a look at the status panel (heart icon) to see details about their state of health.",

"helpMenuText_health_wounds": {
Existing	"english": "Doctors show their true strength when dealing with badly wounded colonists. When push comes to shove and the colony needs to be defended against raiders, injuries are inevitable. Colonists can lose consciousness on the battlefield. While they are losing blood and holding on to dear live, a doctor can rush out, bandage their wounds and administer healing potions to prevent the worst.",

Correction	"english": "Doctors show their true strength when dealing with badly wounded colonists. When push comes to shove and the colony needs to be defended against raiders, injuries are inevitable. Colonists can lose consciousness on the battlefield. While they are losing blood and holding on to dear life, a doctor can rush out, bandage their wounds and administer healing potions to prevent the worst.",

"helpMenuText_immigration_expectations": {
Existing	"english": "Once the colony starts growing and getting more and more wealthy, the colonists want to have a piece of the pie as well. They start expecting good food, a nice looking, comfortable home and a degree of general life statisfaction.
Not meeting these expectations does not turn the colonists against you, but it does prevent future growth: As migrants are considering your colony, they take the ameneties and benefits of living in your colony into account. If your colonists' expectations are not met, you can not convince new people to join!",

Correction	"english": "Once the colony starts growing and getting more and more wealthy, the colonists want to have a piece of the pie as well. They start expecting good food, a nice looking, comfortable home and a degree of general life statisfaction.
Not meeting these expectations does not turn the colonists against you, but it does prevent future growth. As migrants are considering your colony, they take the ameneties and benefits of living in your colony into account. If your colonists' expectations are not met, you can not convince new people to join!",

"helpMenuText_professions_experience": {
Existing	"english": "The colonists stage in their profession is shown with the stars in the job panel. With every completed task, your colonists gather experience for the relevant profession.\nYou can see their experience in the job panel and use the promote button to unlock the next level in their career. A higher level usually comes with new skills that allows them to use better tools and craft more advanced items.",

Correction	"english": "The colonists stage in their profession is shown with the stars in the job panel. With every completed task, your colonists gather experience for their relevant profession.\nYou can see their experience in the job panel and use the promote button to unlock the next level in their career. A higher level usually comes with new skills that allows them to use better tools and craft more advanced items.",

"helpMenuText_professions_education": {
existing	"english": "Sometimes you just can’t wait for learning by doing and your colonists need to look up how to do more complicated stuff to advance to the next stage in their career more easily. Build a book shelf so they can pick up books about their profession and gather experience much faster.
Soldiers are advised to train for combat with a training dummy, since that way has been shown to be less prone to injuries than making a fellow colonist their sparring partner.",

(minor) correction  "english": "Sometimes you just can’t wait for learning by doing, and your colonists need to look up how to do more complicated stuff to advance to the next stage in their career more easily. Build a book shelf so they can pick up books about their profession and gather experience much faster.
Soldiers are advised to train for combat with a training dummy, since that way has been shown to be less prone to injuries than making a fellow colonist their sparring partner.",

"helpMenuText_mood_inspiration": {
Existing	"english": "On the other hand, your colonists could be having the time of their lives. If they are really happy, they can enter a state of inspiration in which they work with semmingly unlimited energy without needing any sleep! When they reach this rare state, they just cannot stop smiling.",

Correction	"english": "On the other hand, your colonists could be having the time of their lives. If they are really happy, they can enter a state of inspiration in which they work with seeming unlimited energy, without needing any sleep! When they reach this rare state, they just cannot stop smiling.",

"helpMenuText_wishes_satisfaction": {

Existing	"english": "If you fulfill more and more wishes of your colonist, they are going to become ever more satisfied with the life in the colony. This satisfaction is not only necessary for attracting new migrants, but has some long term impact as well: With each satisfaction level, your colonist earns a life satisfaction point. Once the colonist has enough of them, these points can be used to change one of their fundamental traits.
For example, someone suffering from pessimism might be a real drag on the colony. However, if the colonist accumulates enough life satisfaction points, you can let them forget the pessimistic trait and replace it with something positive.",

Correction	"english": "If you fulfill more and more wishes of your colonist, they are going to become ever more satisfied with their life in the colony. This satisfaction is not only necessary for attracting new migrants, but has a long term impact as well. With each satisfaction level, your colonist earns a life satisfaction point. Once the colonist has enough of them, these points can be used to change one of their fundamental traits.
For example: Someone suffering from pessimism might be a real drag on the colony. However, if the colonist accumulates enough life satisfaction points, you can let them forget the pessimistic trait and replace it with something positive.",

**Comment by Ponzel** [comment]
all fixed
