### ISSUE TITLE
english grammar corrections for equipment.json

### ISSUE THREAD

**Issue by aiydee** [Ponzel/FoundersFortuneLocalization#42]
"equipmentDescription_woodenClub": {
Existing	"english": "This plain club is used by Tikigoblins. It might be of special value for collectors!",

Correction	"english": "This plain club is used by Tikigoblins. It might be of special value to collectors!",

"equipmentDescription_armorIron": {
Existing	"english": "Takes long to produce, but protects the bearer pretty well.",

Correction	"english": "Takes a long time to produce, but protects the bearer pretty well.",

"equipmentDescription_doctorRobe0": {
Existing	"english": "Offers minor protection against contagious diseases. Very useful for doctors as they have a lot of contact with their ill patients.",

(minor)correction	"english": "Offers minor protection against contagious diseases. Very useful for doctors, as they have a lot of contact with their ill patients.",

"equipmentDescription_doctorRobe1": {
Existing	"english": "Protects the wearer from contagious diseases. Very useful for doctors as they have a lot of contact with their ill patients.",

(minor)correction "english": "Protects the wearer from contagious diseases. Very useful for doctors, as they have a lot of contact with their ill patients.",

**Comment by Ponzel** [comment]
fixed
