### ISSUE TITLE
English grammar corrections:  gameconstructionobjects.json

### ISSUE THREAD

**Issue by aiydee** [Ponzel/FoundersFortuneLocalization#43]
Quite minor this one.  

"stoneWallDefense0": {
Existing	"english": "Fort Fortification",

Suggestion	"english": "Stone Fortification",

"stoneWallDefense1": {
Existing	"english": "Brick Fortification",

Suggestion	"english": "Reinforced stone Fortification",

"stoneWallDefense1Description": {
Existing	"english": "Let your enemys tremble with fear when they see this master piece of a wall!",

(Minor)correction	"english": "Let your enemies tremble with fear when they see this masterpiece of a wall!",

**Comment by Ponzel** [comment]
fixed, except the brick fortification, because "stone" and "reinforced stone" is terribly close to each other.
