### ISSUE TITLE
English grammar/spelling corrections: gameMessages.json

### ISSUE THREAD

**Issue by aiydee** [Ponzel/FoundersFortuneLocalization#44]
"notificationTitle_ColonistTerribleMood": {
Existing	"english": "Desparation",

Typocorrected	"english": "Desperation",

"messageText_TutorialHealing": {
Existing	"english": "A colonist is wounded! Make sure they gets enough sleep to rest their body. An experienced doctor can create more advanced remedies at the potion lab.",

Small correction	"english": "A colonist is wounded! Make sure they get enough sleep to rest their body. An experienced doctor can create more advanced remedies at the potion lab.",

"messageText_LimpingBecauseOfBadSplintTreatment": {
Existing	"english": "It's a begginer's mistake, but can also happen to experienced doctors: Someone messed up the splints to cure %firstName%'s broken leg. It's no longer broken, but now %heShe%'s limping permanently and can't walk as fast as %heShe% used to.",
Correction	"english": "It's a beginner's mistake, but can also happen to experienced doctors: Someone messed up the splints to cure %firstName%'s broken leg. It's no longer broken, but now %heShe%'s limping permanently and can't walk as fast as %heShe% used to.",

**Comment by Ponzel** [comment]
fixed
