### ISSUE TITLE
English Grammar/Spelling corrections:  gameObjects.json

### ISSUE THREAD

**Issue by aiydee** [Ponzel/FoundersFortuneLocalization#45]
"foodShelfKitchenDescription": {
Original	"english": "What better place to store your kitchen food than on this gorgeous shelf?",

Suggestion	"english": "What better place to store your kitchen food than on this gorgeous shelf!",
(In English being rhetorical it should be a statement, not a question)

"beerRefillBarrelDescription": {
Existing	"english": "As a means of storage and the origin of fresh beer, beer barrel is of high importance to all colonies out there (Well, as long as there is some left in there...). You'll see how happy your colonists get when you allow them to fill up their mugs. Cheers!",

Minor Correction	"english": "As a means of storage and the origin of fresh beer, a beer barrel is of high importance to all colonies out there (Well, as long as there is some left in there...). You'll see how happy your colonists get when you allow them to fill up their mugs. Cheers!",

Note:  this applies for most Shelves/Wardrobes.   I'll only include once.
"shelfWoodPlanks0Variation1Description": {
Existing	"english": "This quickly assembled wooden shelf is the ideal storage opportunity for random stuff.",

Correction	"english": "This quickly assembled wooden shelf is the ideal storage location for random stuff.",

(Again, multiple iterations of this.  Will only include 1 example)
"potWood0Variation6Description": {
Existing	"english": "A simple wooden bucket with a red fall flower planted in it. It's scent is entchanting. Sometimes it's the simple things that make you happy the most.",

Correction	"english": "A simple wooden bucket with a red fall flower planted in it. It's scent is entchanting. Sometimes it's the simple things that make you the most happy.",

"tikiHang0": {
Original	"english": "Mysthical Tiki Artefact",

Correction	"english": "Mystical Tiki Artefact",

"bookStandDescription": {
Original	"english": "This book stand can be used for research. Smart colonists can analyze crystals to generate research points. Once enough research has been conducted, new buildings are unlocked.",

Suggestion	"english": "This book stand can be used for research. Smart colonists can analyze crystals to generate research points. Once enough research has been conducted, new technologies are unlocked.",
Buildings in context given sounds like a house.  I appreciate you mean that it unlocks new objects to build.  Another suggestion maybe: Once enough research has been conducted, new buildable objects are unlocked.

"breweryDescription": {
Original	"english": "This masterpiece of brewing technology enables you to brewing the finest beer for your colony. All you need now is an experienced brewmaster and you can get started!",

Correction	"english": "This masterpiece of brewing technology enables you to brew the finest beer for your colony. All you need now is an experienced brewmaster and you can get started!",

"bowmaker": {
Original	"english": "Bowmaker's Workshop",

Correction	"english": "Bowyer's Workshop",

"wellWoodDescription": {
Original	"english": "Some call it irrigation system, others think of it more as a hole with water in it. No matter how you call it - wells play an important role when you want your crops to receive good care. Plants that have been watered correctly have been reported to yield double or triple harvests!",

Correction	"english": "Some call it an irrigation system, others think of it more as a hole with water in it. No matter how you call it - wells play an important role when you want your crops to receive good care. Plants that have been watered correctly have been reported to yield double or triple harvests!",

"graveSimpleDescription": {
Original	"english": "In the event of death, this is the simpliest solution. Your enemies deserve no better than this for sure...",

Spelling		"english": "In the event of death, this is the simplest solution. Your enemies deserve no better than this for sure...",

**Comment by Ponzel** [comment]
thanks, fixed for Alpha 9
