### ISSUE TITLE
English: Small change to professions.json

### ISSUE THREAD

**Issue by aiydee** [Ponzel/FoundersFortuneLocalization#46]
Just 1 letter to change.  Remove the s from gathers to make it parse correctly in English

"professionDesc_Farmer": {
Original	"english": "Farmers are responsible for food production and cooking food. When not busy, they also gathers cotton.",

minorchg	"english": "Farmers are responsible for food production and cooking food. When not busy, they also gather cotton.",

**Comment by Ponzel** [comment]
fixed
