### ISSUE TITLE
English grammar correction:  thoughts.json

### ISSUE THREAD

**Issue by aiydee** [Ponzel/FoundersFortuneLocalization#47]
"thoughtDesc_MyFurnitureDestroyed": {
Original	"english": "I had some pretty nice furniture in my bedroom, but somebody completely demolished them!",

Correction	"english": "I had some pretty nice furniture in my bedroom, but somebody completely demolished it!",

"moodPhrase_RefusingWork1": {
Original	"english": "Burnout has become the better of me. I can't work any more.",

Correction	"english": "Burnout has the better of me. I can't work any more.",

**Comment by Ponzel** [comment]
thanks, fixed
