### ISSUE TITLE
Character limits for word "Experience"

### ISSUE THREAD

**Issue by macieqx** [Ponzel/FoundersFortuneLocalization#51]
There is limit of probably 11 characters for word experience in file uiIngame.json

Polish word for this has 13 letters, please expand maximum number of characters available.

**Comment by Ponzel** [comment]
Can you upload a screenshot where it shows the location where it's not displayed correctly?
In the crew selection it seems to work.

We plan to release Alpha 9 on August 23rd. We can include polish only if it reaches 90% a couple of days before that.

**Comment by Ponzel** [comment]
Closing this because of missing answer.

Contact me if it should be reopened.
