### ISSUE TITLE
English translation maybe wrong

### ISSUE THREAD

**Issue by Loikas** [Ponzel/FoundersFortuneLocalization#58]
In the diplomaticRelations on line 46 the english translation may not be correct
![TransWrong](https://user-images.githubusercontent.com/50876764/63289938-96bd2b80-c2c0-11e9-80da-bd16126691a3.png)

**Comment by Loikas** [comment]
In the gameobjects.json there is a mistake in the english translation
![UitroeptekenPunt](https://user-images.githubusercontent.com/50876764/63373752-bcae0300-c388-11e9-9631-580ebf5ec609.png)
On the end there are a exclamationmark aswell as a point.

**Comment by Loikas** [comment]
Another one, in traits.json there is no he she on the line where the xenophobe one has one, it only says: "he is quick to trust"
there is no %cap-heShe%
![no he-She](https://user-images.githubusercontent.com/50876764/63374369-f6cbd480-c389-11e9-8638-700c18df588d.png)

**Comment by Loikas** [comment]
In equipment.json, mechandise instead of merchandise
![mechandise](https://user-images.githubusercontent.com/50876764/63376753-d8b4a300-c38e-11e9-8592-b26932c5c6df.png)

**Comment by Ponzel** [comment]
Thanks Loikas, fixed it.
