### ISSUE TITLE
English mistakes in encyclopedia.json (edit: and more)

### ISSUE THREAD

**Issue by Wyllo** [Ponzel/FoundersFortuneLocalization#59]
Line 341 → "**are are** not going to”  → remove one are 

Line 397 → “laying in **bed** offers their **the** bodies” → Laying in a bed offers their bodies 

Line 463 → “holding on to dear **live**” → life 

Line 543 → “you **can not** convince”  → cannot 

Line 732 : 
→“everyone has **their** breaking point” → everyone has his/her breaking point 

→”(**no not** the dark side in this case)” → no not ?

**Comment by Wyllo** [comment]
### English mistakes in equipment.json 

Line 68 → “to secure the **mechandise**” → merchandise 

Line 359 → “when it comes to dealing **damage**!",” → damages 

Line 480 → “Takes a long time to **produce**,” → to be produced 

Line 518 → “**Noone**” → None

Line 897 → “Sowing and watering **takes** a little less time!" → take 

### English mistakes in expectations.json

Line 48 → “doesn't care about **a home** at the moment." → having a home 

Line 243 →  "Very happy **with life**", → with his/her life 

Line 258 → "Satisfied **with life**", → with his/her life

Line 288 → "Not satisfied **with life**", → with his/her life

Line 642 → "Click to **show sleeping spot**" → show his/her sleeping spot

**Comment by Ponzel** [comment]
Thanks fixed it, expect

**their -> hisHer**
It's a big topic how to use he or she in texts to make it not seem like anyone is excluded. Saying "they" seems to be an acceptable, quick, and easy solution.

**dealing damage**
I've heard this before and a quick search made it seem ok.

**about a home**
I changed it to %hisHer% home. The sentence is not about "having a home", but instead they don't care about "anything home related. Not about having one and not about how big or beautiful it is.

**happy with (hisHer) life** and related things
I believe you can skip his or her, can't you?

**Comment by Wyllo** [comment]
> **happy with (hisHer) life** and related things
> I believe you can skip his or her, can't you?

Well, grammar is something mutable in all languages and even something agrammatical is not completely "wrong". It's just wrong according to a specific standard.  Simple example : the popularization of "he don't" instead of "he doesn't". 
Furthermore, in the sentence "He is happy with life",  life is a concept/notion "unbouded".
On the other hand, if we add a possessive pronoun, it creates a subcategory within the concept of life. Therefore, we're not talking about life in general but someone's life. 
This is of course a slight difference but yes I think you can skip the pronoun because even though it does not appear, it's still implied. 
Anyway, the most essential thing in a language is first to be understood and not to be fully grammatically correct. 
In my opinion, it seems a bit odd without his / her but I'm just a grumpy linguist ahah. 
Plus, if you pay attention to the translations of the sentence, the possessive pronoun appears.

**Comment by aiydee** [comment]
I agree with Ponzel.  
The thing to consider is that these are being shown as "This is my current thought"  
I do not think "I'm happy with his life"  
I might think "I'm happy with my life"  
At the same time, it'd be acceptable to say "I'm happy with life"  

So yes, linguistically, if you were describing someone in a third party narrative, then yes 'his/her'.  
But this is "Current thoughts".  Which implies the current thought of that colonist and they will not think in the his/her narrative.  

This is what makes editing JSONs so difficult.  It's impersonal.  It lends to 3rd person.  Yet quite a few things are written in 1st person, but JSON gives no indication of 1st or 3rd.

**Comment by Ponzel** [comment]
Ah, small correction:
Aiydee, you're correct that things in thoughts.json are in first person, but the example with "%firstName% is happy with (%hisHer%) life is actually displayed when you hover over their expectation icons and is written in third person.

**Comment by aiydee** [comment]
Hmmm.  You are correct.   Carry on.  (As I said.  JSON is impersonal and makes it hard at times)  
Which leads to the next horrible question:  
Are all thoughts meant to be 1st person or 3rd person?  
If 1st person, then all should be written as 1st person.
If 3rd person, all should be written as 3rd person.  
(For sake of consistency)

**Comment by Ponzel** [comment]
Thoughts are supposed to always be in 1st person.
We'r not discussing a "thought" here in the Founders' Fortune sense though, this text appears in a different part of the menu. Or did you mean something else?
