### ISSUE TITLE
Notification text too long

### ISSUE THREAD

**Issue by Loikas** [Ponzel/FoundersFortuneLocalization#62]
![DoubleBonfire](https://user-images.githubusercontent.com/50876764/63424428-b3677980-c40e-11e9-98a9-5cd9389c2b32.png)
The message that shows that you have to build a bonfire is too long

**Comment by Ponzel** [comment]
Can you shorten it?

**Comment by Loikas** [comment]
Already tried but this is the shortest translation i can think of

**Comment by Ponzel** [comment]
Ah, you mean because it's in 2 lines? That's fine :)
That's why the box is big enough to fit 2 lines.
