### ISSUE TITLE
Just a small mistake in steam.md (edit: +gameMessages.json)

### ISSUE THREAD

**Issue by Wyllo** [Ponzel/FoundersFortuneLocalization#64]
Line 934 → These are things we'd like to do and the final results **depends** on the amount →  depend

Plus, I corrected some French mistakes.

**Comment by Wyllo** [comment]
### English mistakes in gameMessages.json 

1. Line 177→ "Colonist lost Consciousness",  → A colonist 

2. Line 192 → “Colonist died", →  A colonist

3. Line 282 → “Colonist joined",  →  A colonist

4. Line 297 → "**Migrants** are leaving", → A migrant is leaving _((“the” instead of “a” is also possible because “the” is an anaphoric definite article and the migrant has already been introduced when he arrived.))_ 

5. Line 357 → "Colonist has an allergic reaction", → A colonist 

6. Line 478→  "Colonist is missing %hisHer% Possessions", →  A colonist

7. Line 759 → "**Migrants** arrived!", → A migrant

8. Line 774 → "A **few migrants** **have** seen our fire signal and just arrived in a small boat. 
Send a colonist to accept **them**!", → A migrant has seen our fire signal and just arrived in a small boat. Send a colonist to accept him!

9. Line 789 →   "Trader arrived!" → A trader

10. Line 1044 →  “A colonist is wounded! Make sure **they** get enough sleep to rest **their** body”.  → Make sure he gets enough sleep to rest his body

**Comment by Ponzel** [comment]
Hm, so the fundamental question if we should add articles to notifications.
I prefer how they look and read without articles, but I'm not sure if it's 100% correct English.
However, looking at other games, skipping the article seems to work fine (https://steamuserimages-a.akamaihd.net/ugc/956357161381214416/D478912AC6783C2D7274CEA93E0E077ADCB43DB1/), so I'm inclined to keep it that way.

You could have an discussion how to handle gendered notifications like "they" vs "him/her", but I feel like "they" is fine as a solution when you don't know the gender.

Fixed all the rest, thanks :)
