### ISSUE TITLE
notEnough in gameMessages.json

### ISSUE THREAD

**Issue by FourwingsY** [Ponzel/FoundersFortuneLocalization#66]
"english": "Not enough %resource%!",
"korean": "%resource%#{가} 부족합니다!"

**Comment by Ponzel** [comment]
done!
It'll be in the game starting from Alpha 9.1, but you can already change it in the files here.
Please close this issue once you've updated it in gameMessages.json.

**Comment by FourwingsY** [comment]
@Ponzel would you add me on repo?

**Comment by Ponzel** [comment]
Oh sorry @FourwingsY I thought I'd already done that!
You should have got an email now.

**Comment by FourwingsY** [comment]
Done!
