### ISSUE TITLE
Just a little typo in german language: fruendlich

### ISSUE THREAD

**Issue by SirTobyB** [Ponzel/FoundersFortuneLocalization#71]
Here's the example:

![grafik](https://user-images.githubusercontent.com/26973123/69911498-98989e00-141c-11ea-88d9-90049ef8dff7.png)

`fruendlich` should be `freundlich` of course. Would try to fix this myself but i read on the forums, that you prefer an issue for mistakes in the german language. 😉 

Greetings
Sir Toby

**Comment by SirTobyB** [comment]
Found just another little typo:  
![grafik](https://user-images.githubusercontent.com/26973123/69999493-106be300-1559-11ea-89f2-67b8cdb8f390.png)

I think, it should be `Einer der`.

**Comment by Ponzel** [comment]
Thanks SirToby, all fixed!
