### ISSUE TITLE
Mistakes in english (Architecture Update)

### ISSUE THREAD

**Issue by Patrador** [Ponzel/FoundersFortuneLocalization#72]
Hello, here are some small mistakes in gameObjets.json :
- stockpileStoneDescription : "upt o" > "up to"
- stockpileCoinBigDescription : "upt o" > "up to"
- stockpileIronOreDescription : "sipmle" > "simple" and "up ot" > "up to"

**Comment by Ponzel** [comment]
Thanks, all fixed!
Seems I was in a hurry when writing "up to" :D
