### ISSUE TITLE
Alpha 12 localisation bugs/mistakes

### ISSUE THREAD

**Issue by Patrador** [Ponzel/FoundersFortuneLocalization#77]
### Gender bugs:
- In _gameMessages.json_ line 864 - 869 and _relationships.json_ line 135 - 145: "Not impressed" and "impressed"
![image](https://user-images.githubusercontent.com/43299105/74234041-41d8fb80-4ccc-11ea-926e-ac508a46fd0e.png)
![image](https://user-images.githubusercontent.com/43299105/74234304-c9bf0580-4ccc-11ea-8e6e-5d48093c25e9.png)

### English mistakes:
- In _gameConstructionObjects.json_ line 503: "Happy Cirlce Carpet" > "Happy Circle Carpet"
- In _relationships.json_ line 93: "%grandpaGrandma" the % is missing at the end (in german too)

### Missing translation:
- Description of "Colonist Died too early" (because in _thoughts.json_ the title id has been changed but not the description id)
![image](https://user-images.githubusercontent.com/43299105/74234870-2242d280-4cce-11ea-9bb1-c28ffb13a222.png)
- Title of "Chilhood Experiences"
![image](https://user-images.githubusercontent.com/43299105/74272533-19bebc00-4d0f-11ea-9e16-c949108c0449.png)

**Comment by Ponzel** [comment]
Thanks, fixed them all. The french thing requires a new translation in thoughts.json now, but otherwise, everything ok.
