### ISSUE TITLE
French

### ISSUE THREAD

**Issue by Cdrix** [Ponzel/FoundersFortuneLocalization#78]
Propriétair ----> It's "Propriétaire" ("e" is missing)

![Screenshot_1](https://user-images.githubusercontent.com/40391221/83329551-73310380-a28a-11ea-812e-514b1f936c37.png)

**Comment by Cdrix** [comment]
The notification for the level 4 of the forester was also in English

**Comment by Cdrix** [comment]
The option "speak (parler)" for an animal ... strange no ? :-))) Why not : "Take care..." or something like that.

![sheep](https://user-images.githubusercontent.com/40391221/83329661-02d6b200-a28b-11ea-95fa-2b041dbfee9a.png)

**Comment by Cdrix** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/40391221/83348795-07a17180-a330-11ea-86d9-9c5712246825.png)

**Comment by Cdrix** [comment]
@Ponzel

**Comment by Ponzel** [comment]
Thanks!
Notification level: I just added this with a minor update, it just hasn't been translated yet.
Talking to sheep: Yeah it's funny and intentional. Caring will come later, when the gameplay around it is implemented.

Fixed the rest.
