### ISSUE TITLE
Colonist panel

### ISSUE THREAD

**Issue by Cdrix** [Ponzel/FoundersFortuneLocalization#9]
1) Texts too short in the panel
2) Lack of words : "Ragoût de" ...... potirons 

![Screenshot_4](https://user-images.githubusercontent.com/40391221/56598477-dadf3e80-65f4-11e9-8de6-bcb118783f7b.png)

**Comment by Cdrix** [comment]
Commencer la partie : panel too short

![Screenshot_5](https://user-images.githubusercontent.com/40391221/56598607-167a0880-65f5-11e9-86a4-2c5a81adc963.png)

**Comment by Ponzel** [comment]
Also fixed!
